version: '3'
services:
  # DB設定
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - "4306:3306"

  # バックエンド設定
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # image: rails:dev
    volumes:
      - ./backend:/myapp
      - gem_data:/usr/local/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3001:3000
    depends_on:
      - db

# フロント設定
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    # command: sh -c "cd /usr/src/app && yarn && yarn start"
    command: 'yarn dev'
    ports:
      - "4000:3000"

# データ永続化用
volumes:
  mysql-data:
  gem_data: